### ISSUE TITLE
Is OPENAI’s text-to-speech model (tts-1/tts-1-hd) currently not supported? Will support be added in the future?

### ISSUE THREAD

**Issue by null119** [OpenRouterTeam/openrouter-examples-python#1]
When using the API interface (https://openrouter.ai/api/v1) to perform OPENAI text-to-speech (https://openrouter.ai/api/v1/audio/speech), an error code 1010 is reported. Then check the documentation on the website. The openai tts-1/tts-1-hd model was not found. Will you consider adding support later?

**Comment by alexanderatallah** [comment]
no text to speech yet!
